name: Release

on:
  push:
    #branches: [ "release" ]
    tags: test-[0-9]+.*

jobs:
  build:
    outputs:
      version: ${{ steps.info.outputs.version }}
      changes: ${{ steps.info.outputs.changelog }}
    runs-on: ubuntu-latest
    needs: info
    steps:
    - uses: actions/checkout@v3
    - name: Get Version
      id: info
      run: |
        echo "version=$(make ci-version)" >> $GITHUB_OUTPUT
        echo "changelog=$(make ci-changelog)" | jq -nR '[inputs | .] | join("\n")' >> $GITHUB_OUTPUT
    - run: |
        echo ${{ steps.info.outputs.version }}
    - name: Install Dependencies
      run: sudo apt install asciidoc-base
    - name: Release tarball
      run: |
        VERSION=$(make ci-version)
        git archive --prefix=daemon-manager-"$VERSION"/ HEAD -o daemon-manager-"$VERSION".tar.gz
    - name: Debian package
      run: |
        set -e
        set -x
        echo Building package for ${{ steps.info.outputs.version }}
        git clone . debian
        cd debian
        git fetch ${{ github.repositoryUrl }}
        git checkout debian
        git merge -m "Merging ${{ steps.info.outputs.version }} into debian" ${{ github.ref_name }}
        (make ci-changelog | perl -pe 's/^[^\s].*$/$& unstable; urgency=medium/'
         cat debian/changelog) > debian/changelog.new
        mv debian/changelog{.new,}
        git add debian/changelog
        git commit -m "debian/changelog: Version ${{ steps.info.outputs.version }}"
        dpkg-buildpackage -rfakeroot

    - name: Tarball artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: daemon-manager-${{ steps.info.outputs.version }}.tar.gz
        path: daemon-manager-*.tar.gz
        if-no-files-found: error
        retention-days: 1 ### for my tests, remove me when it works!!
    - name: Deban package artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: daemon-manager_${{ steps.info.outputs.version }}_amd64.deb
        path: daemon-manager-*.deb
        if-no-files-found: error
        retention-days: 1 ### for my tests, remove me when it works!!

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          daemon-manager-*.tar.gz
          daemon-manager-*.deb
        body: "# ${{ steps.info.outputs.changelog }}"
