name: Release

on:
  push:
    #branches: [ "release" ]
    tags: test-[0-9]+.*

jobs:
  build:
    defaults:
      run:
        shell: bash -xeo pipefail -c {0}
    outputs:
      version: ${{ steps.info.outputs.version }}
      changes: ${{ steps.info.outputs.changelog }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Version and Changelog
      id: info
      run: |
        echo "version=$(make ci-version)" >> $GITHUB_OUTPUT
        echo "changelog=$(make ci-changelog | jq -nR '[inputs | .] | join("\n")')" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
    - run: echo '${{ steps.info.outputs.version }}'
#    - run: echo ${{ steps.info.outputs.changelog }}
    - run: echo "${INPUT_CHANGELOG}"
      with:
        changelog: ${{ fromJSON(steps.info.outputs.changelog) }}
    - run: test -n "$INPUT_CHANGELOG"
      with:
        changelog: ${{ fromJSON(steps.info.outputs.changelog) }}
    - name: Install Dependencies
      run: sudo apt install asciidoc-base debhelper
    - name: Release tarball
      run: |
        make release
    - name: Debian package
      run: |
        echo "Building package for $INPUT_VERSION"
        git branch --track debian origin/debian
        git clone -b debian . debian
        cd debian
        git config user.name "CI Build Bot"
        git config user.email "david@porkrind.org"
        git merge -m "Merging $INPUT_VERSION into debian" ${{ github.ref_name }}
        (echo "$INPUT_CHANGELOG" | perl -pe 's/^[^\s].*$/$& unstable; urgency=medium/'
         cat debian/changelog) > debian/changelog.new
        mv debian/changelog{.new,}
        git add debian/changelog
        git commit -m "debian/changelog: Version $INPUT_VERSION"
        dpkg-buildpackage -rfakeroot
      with:
        changelog: ${{ fromJSON(steps.info.outputs.changelog) }}
        version: ${{ steps.info.outputs.version }}

    - name: Tarball artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: daemon-manager-${{ steps.info.outputs.version }}.tar.gz
        path: daemon-manager-*.tar.gz
        if-no-files-found: error
        retention-days: 1 ### for my tests, remove me when it works!!
    - name: Deban package artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: daemon-manager_${{ steps.info.outputs.version }}_amd64.deb
        path: daemon-manager_*.deb
        if-no-files-found: error
        retention-days: 1 ### for my tests, remove me when it works!!

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          daemon-manager-*.tar.gz
          daemon-manager_*.deb
          daemon-manager-dbgsym_*.ddeb
        body: "# ${{ fromJSON(steps.info.outputs.changelog) }}"
